version: '3.8'
services:
  mongo:
    image: mongo:4
    container_name: mongo-replica
    ports:
      - 27017:27017
    command: ["mongod", "--replSet", "rs0", "--bind_ip_all"]
    volumes:
      - mongo-data:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"


volumes:
  mongo-data:
