apiVersion: v1
kind: Pod
metadata:
  name: backend-app-pod
  labels:
    name: backend-app-pod
    app: demo-voting-app
spec:
  containers:
    - name: backend-app
      image: gipsyone/backend-app:latest
      ports:
        - containerPort: 80