apiVersion: v1
kind: Service
metadata:
  name: backend-app
  labels:
    name: backend-app-service
    app: demo-voting-app
spec:
  type: NodePort
  ports:
    - port: 4000
      targetPort: 4000
      nodePort: 30001
  selector:
    name: backend-app-pod
    app: demo-voting-app